FROM alpine:3.7

RUN apk add --update \
    bash \
    python3 \
    python3-dev \
    py-pip \
    build-base \
    libffi-dev \
    libxml2-dev \
    libxslt-dev \
    yajl-dev \
    openssl-dev \
  && rm -rf /var/cache/apk/*

RUN adduser -D openDataGraph

WORKDIR /home/openDataGraph

COPY requirements.txt requirements.txt
RUN python3 -m venv venv \
    && venv/bin/pip install --upgrade pip setuptools \
    && venv/bin/pip install -r requirements.txt

RUN venv/bin/pip install gunicorn

COPY . ./

RUN mkdir db
RUN chown -R openDataGraph:openDataGraph ./ \
    && chmod +x boot.sh

USER openDataGraph

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
