version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - data-volume:/data/db
volumes:
    data-volume:
