FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y \
  libyajl-dev \
  python3-pip \
  python3-dev \
  python3-venv

RUN rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash openDataGraph
WORKDIR /home/openDataGraph/app

COPY requirements.txt requirements.txt
RUN python3 -m venv venv \
    && venv/bin/pip install --upgrade pip setuptools \
    && venv/bin/pip install -r requirements.txt

COPY --chown=openDataGraph:openDataGraph . ./

RUN venv/bin/pip install gunicorn
RUN mkdir db && chown -R openDataGraph:openDataGraph db && chown openDataGraph:openDataGraph .
RUN chmod +x boot.sh

USER openDataGraph

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
