version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - CONTAINER_TYPE=web
    depends_on:
      - mongodb
      - neo4j
      - celery-job-worker
      - celery-mail-worker
    volumes:
      - /tmp:${UPLOAD_FOLDER}
      - sqlite-volume:/data/db
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - data-volume:/data/db
  neo4j:
    image: neo4j:3.5
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ${HOME}/neo4j/data:/data
      - ${HOME}/neo4j/logs:/logs
      - ${HOME}/neo4j/import:/import
      - ${HOME}/neo4j/plugins:/plugins
    environment:
      # Raise memory limits
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASS}
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
  celery-job-worker:
    build:
      context: "."
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - CONTAINER_TYPE=celery_job_worker
    volumes:
      - /tmp:${UPLOAD_FOLDER}
      - ${SEMREP_DIR}:${SEMREP_DIR}
  celery-mail-worker:
    build:
      context: "."
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - CONTAINER_TYPE=celery_mail_worker
volumes:
    data-volume:
    sqlite-volume:
