version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
  mongo:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
