source venv/bin/activate
export FLASK_APP=disease_graph_run_app.py
export FLASK_ENV=development
export MAIL_SERVER=localhost
export MAIL_PORT=8025
export MONGODB_HOST='127.0.0.1'
export MONGODB_PORT=27017
export MONGODB_NAME=DiseaseGraph
export UPLOAD_FOLDER='/tmp/'